I'm sorry, but an uncaught exception occurred.

Compiling ATL code at game/script.rpy:6
  File "game/script.rpy", line 24, in script
    show leenayoung_basic
Exception: Not a displayable: ('이나영_기본.png', 0.1)

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 24, in script
    show leenayoung_basic
  File "C:\Users\asus\Desktop\renpy-8.1.3-sdk\renpy\ast.py", line 1428, in execute
    show_imspec(self.imspec, atl=getattr(self, "atl", None))
  File "C:\Users\asus\Desktop\renpy-8.1.3-sdk\renpy\ast.py", line 1391, in show_imspec
    renpy.config.show(name,
  File "C:\Users\asus\Desktop\renpy-8.1.3-sdk\renpy\exports.py", line 733, in show
    if not base.find_target() and renpy.config.missing_show:
  File "C:\Users\asus\Desktop\renpy-8.1.3-sdk\renpy\display\image.py", line 421, in find_target
    self.target = target._duplicate(a)
  File "C:\Users\asus\Desktop\renpy-8.1.3-sdk\renpy\display\transform.py", line 1049, in _duplicate
    rv.take_execution_state(self)
  File "C:\Users\asus\Desktop\renpy-8.1.3-sdk\renpy\atl.py", line 418, in take_execution_state
    block = self.compile()
  File "C:\Users\asus\Desktop\renpy-8.1.3-sdk\renpy\atl.py", line 543, in compile
    block = self.atl.compile(self.context)
  File "C:\Users\asus\Desktop\renpy-8.1.3-sdk\renpy\atl.py", line 745, in compile
    statements = [ i.compile(ctx) for i in self.statements ]
  File "C:\Users\asus\Desktop\renpy-8.1.3-sdk\renpy\atl.py", line 745, in <listcomp>
    statements = [ i.compile(ctx) for i in self.statements ]
  File "C:\Users\asus\Desktop\renpy-8.1.3-sdk\renpy\atl.py", line 1051, in compile
    child = renpy.easy.displayable(child)
  File "C:\Users\asus\Desktop\renpy-8.1.3-sdk\renpy\easy.py", line 145, in displayable
    raise Exception("Not a displayable: %r" % (d,))
Exception: Not a displayable: ('이나영_기본.png', 0.1)

Windows-10-10.0.22621 AMD64
Ren'Py 8.1.3.23091805
Our Blue Horizon 1.0
Sat Oct 14 02:30:04 2023
